version: '2'
services:
  demobugtracker-app:
    image: demobugtracker
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://demobugtracker-mysql:3306/demobugtracker?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  demobugtracker-mysql:
    extends:
      file: mysql.yml
      service: demobugtracker-mysql
